-- Create a test broker account first
-- Insert sample broker profile (will be created when first user registers)
-- For now, we'll use a placeholder UUID that will be replaced

-- Insert sample properties with realistic data
INSERT INTO properties (
  broker_id,
  title,
  description,
  type,
  price,
  currency,
  price_eur,
  size_sqm,
  bedrooms,
  bathrooms,
  floor,
  total_floors,
  construction_type,
  year_built,
  parking,
  furnished,
  elevator,
  balcony,
  heating_type,
  country,
  city,
  address,
  latitude,
  longitude,
  photos,
  status,
  domus_score
) VALUES
-- Property 1: Sofia Luxury Apartment
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Луксозен апартамент в центъра на София',
  'Просторен тристаен апартамент в сърцето на София, с модерен ремонт и висококачествени материали. Апартаментът разполага с голяма дневна, две спални, две бани и тераса с панорамна гледка към Витоша. Находится в престижна сграда с контролиран достъп и подземен паркинг.',
  'apartment',
  185000,
  'EUR',
  185000,
  120,
  3,
  2,
  5,
  8,
  'Brick',
  2020,
  true,
  true,
  true,
  true,
  'Central',
  'Bulgaria',
  'Sofia',
  'бул. Витоша 125',
  42.6977,
  23.3219,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_eaa0b9ce-e4b8-4162-bdc2-067d20b70dbc.jpg'],
  'active',
  88
),
-- Property 2: Barcelona Beachfront
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Апартамент на първа линия в Барселонета',
  'Уникален апартамент с директна гледка към морето в най-търсения квартал Барселонета. Две спални, модерна кухня, голяма тераса. Перфектен за инвестиция - висока рентабилност от краткосрочни наеми. На 50 метра от плажа.',
  'apartment',
  320000,
  'EUR',
  320000,
  85,
  2,
  1,
  3,
  5,
  'Concrete',
  2018,
  false,
  true,
  true,
  true,
  'Central',
  'Spain',
  'Barcelona',
  'Passeig Marítim de la Barceloneta 15',
  41.3751,
  2.1865,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_29455fd3-28b1-4921-ad56-9b3dcd2815bf.jpg'],
  'active',
  91
),
-- Property 3: Rome Historic Building
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Класически апартамент близо до Ватикана',
  'Очарователен апартамент в историческа сграда от 19-ти век, напълно реновиран със запазване на оригиналните детайли. Високи тавани, паркет, мраморна баня. Тих район с отлична транспортна връзка. Идеален за семейство или инвеститори.',
  'apartment',
  295000,
  'EUR',
  295000,
  95,
  2,
  1,
  2,
  4,
  'Brick',
  1890,
  false,
  false,
  false,
  true,
  'Central',
  'Italy',
  'Rome',
  'Via Cola di Rienzo 234',
  41.9028,
  12.4964,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_1a556f63-6c01-4963-abb9-f28a539aba9e.jpg'],
  'active',
  82
),
-- Property 4: Athens Penthouse
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Пентхаус с тераса и гледка към Акропола',
  'Луксозен пентхаус на последния етаж с невероятна панорамна тераса от 60 кв.м. Три спални, три бани, модерна кухня с висок клас техника. Уникална гледка към Акропола и Партенона. Ексклузивна сграда с басейн и фитнес.',
  'apartment',
  450000,
  'EUR',
  450000,
  145,
  3,
  3,
  7,
  7,
  'Concrete',
  2021,
  true,
  true,
  true,
  true,
  'Central',
  'Greece',
  'Athens',
  'Leof. Vasilissis Sofias 89',
  37.9838,
  23.7275,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_2831fe69-3627-4903-bee5-bdebf581d182.jpg'],
  'active',
  85
),
-- Property 5: Bucharest Modern Apartment
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Модерен апартамент в Примавери, Букурещ',
  'Нов тристаен апартамент в престижния квартал Примавери. Луксозно обзавеждане, smart home система, подово отопление. Сградата предлага 24/7 охрана, фитнес зала и детска площадка. Близо до посолства и международни училища.',
  'apartment',
  220000,
  'EUR',
  220000,
  110,
  3,
  2,
  4,
  6,
  'Concrete',
  2022,
  true,
  true,
  true,
  true,
  'Central',
  'Romania',
  'Bucharest',
  'Strada Aviator Popisteanu 54',
  44.4673,
  26.0784,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_b1c2cbd7-f41c-4c3a-af8e-676f718cb8f3.jpg'],
  'active',
  86
),
-- Property 6: Traditional Bulgarian House
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Автентична българска къща в Стария град',
  'Реновирана традиционна къща в архитектурен резерват. Запазена автентична архитектура с модерни удобства. Три спални, камина, двор с лозе и барбекю. Уникална възможност за собствен бизнес - къща за гости или семеен хотел.',
  'house',
  165000,
  'EUR',
  165000,
  180,
  3,
  2,
  0,
  2,
  'Stone',
  1920,
  true,
  true,
  false,
  false,
  'Wood',
  'Bulgaria',
  'Plovdiv',
  'ул. Съборна 25',
  42.1438,
  24.7495,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_4e64eecc-f5fa-496a-b1cb-12c1ffa51719.jpg'],
  'active',
  79
),
-- Property 7: Spanish Villa with Pool
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Вила с басейн на Коста Брава',
  'Разкошна вила с четири спални и частен басейн. Средиземноморска архитектура, голяма градина с палми и цитрусови дръвчета. Барбекю зона, гараж за две коли. На 5 минути с кола от плажа. Идеална за постоянно живеене или ваканционен дом.',
  'house',
  580000,
  'EUR',
  580000,
  220,
  4,
  3,
  0,
  2,
  'Concrete',
  2015,
  true,
  true,
  false,
  true,
  'Central',
  'Spain',
  'Lloret de Mar',
  'Carrer de les Alzines 45',
  41.6995,
  2.8453,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_cb12b8dc-0c27-4b2e-93ee-215f5810160e.jpg'],
  'active',
  83
),
-- Property 8: Mountain Chalet Bansko
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Планинска вила в Банско до ски писта',
  'Луксозна планинска вила с директен достъп до ски пистата. Три нива, пет спални, сауна, джакузи, камина. Панорамни прозорци с гледка към Пирин. Отлична инвестиция - висока рентабилност от зимен и летен туризъм.',
  'house',
  380000,
  'EUR',
  380000,
  250,
  5,
  4,
  0,
  3,
  'Wood',
  2019,
  true,
  true,
  false,
  true,
  'Central',
  'Bulgaria',
  'Bansko',
  'ул. Пирин 78',
  41.8388,
  23.4871,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_b0f3cb94-1485-4831-bb82-d79618af0dc9.jpg'],
  'active',
  87
),
-- Property 9: Affordable Sofia Apartment
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Двустаен апартамент в Люлин',
  'Практичен двустаен апартамент, подходящ за първо жилище или инвестиция. Светъл, с южно изложение. Близо до метростанция, училища и магазини. Ниски режийни разходи. Отлична цена за София.',
  'apartment',
  85000,
  'EUR',
  85000,
  65,
  2,
  1,
  3,
  9,
  'Panel',
  1985,
  false,
  false,
  true,
  true,
  'Central',
  'Bulgaria',
  'Sofia',
  'бул. Джавахарлал Неру 15',
  42.7105,
  23.2683,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_eaa0b9ce-e4b8-4162-bdc2-067d20b70dbc.jpg'],
  'active',
  75
),
-- Property 10: Investment Opportunity Varna
(
  (SELECT id FROM profiles WHERE account_type = 'broker' LIMIT 1),
  'Апартамент до морето във Варна - инвестиция',
  'Студио на 200 метра от плажа в морската столица. Идеален за краткосрочни наеми през летния сезон. Нова сграда с Act 16, готов за обзавеждане. Очаквана рентабилност 8-10% годишно. Силно търсен район.',
  'apartment',
  68000,
  'EUR',
  68000,
  42,
  1,
  1,
  2,
  6,
  'Concrete',
  2023,
  false,
  false,
  true,
  true,
  'Central',
  'Bulgaria',
  'Varna',
  'бул. Приморски 125',
  43.2047,
  27.9147,
  ARRAY['https://miaoda-site-img.s3cdn.medo.dev/images/KLing_29455fd3-28b1-4921-ad56-9b3dcd2815bf.jpg'],
  'active',
  92
);

-- Insert some sample market data
INSERT INTO market_data (country, city, neighborhood, date, avg_price_sqm, property_type, transaction_count)
VALUES
  ('Bulgaria', 'Sofia', 'Center', '2026-01-01', 1850, 'apartment', 45),
  ('Bulgaria', 'Sofia', 'Lozenets', '2026-01-01', 2100, 'apartment', 38),
  ('Bulgaria', 'Plovdiv', 'Center', '2026-01-01', 1200, 'apartment', 28),
  ('Bulgaria', 'Varna', 'Seaside', '2026-01-01', 1650, 'apartment', 52),
  ('Spain', 'Barcelona', 'Barceloneta', '2026-01-01', 4200, 'apartment', 67),
  ('Italy', 'Rome', 'Vatican', '2026-01-01', 3800, 'apartment', 43),
  ('Greece', 'Athens', 'Center', '2026-01-01', 2900, 'apartment', 56),
  ('Romania', 'Bucharest', 'Primaverii', '2026-01-01', 2400, 'apartment', 34)
ON CONFLICT DO NOTHING;